export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_ERROR = "GET_TOKEN_ERROR";

export const GET_DEVICE_COUNT_REQUEST = "GET_DEVICE_COUNT_REQUEST";
export const GET_DEVICE_COUNT_SUCCESS = "GET_DEVICE_COUNT_SUCCESS";
export const GET_DEVICE_COUNT_ERROR = "GET_DEVICE_COUNT_ERROR";

export const GET_DEVICE_DATA_REQUEST = "GET_DEVICE_DATA_REQUEST";
export const GET_DEVICE_DATA_SUCCESS = "GET_DEVICE_DATA_SUCCESS";
export const GET_DEVICE_DATA_ERROR = "GET_DEVICE_DATA_ERROR";

export const GET_DEVICE_APP_DATA_REQUEST = "GET_DEVICE_APP_DATA_REQUEST";
export const GET_DEVICE_APP_DATA_SUCCESS = "GET_DEVICE_APP_DATA_SUCCESS";
export const GET_DEVICE_APP_DATA_ERROR = "GET_DEVICE_APP_DATA_ERROR";
